### PR TITLE
#158792524 #159051218 design mockups and color palette for the app.

### PR DESCRIPTION
**Pull request by petermwash**
#### What does this PR do?
- Design mockups (wireframes).
- Determine the color palette for the app.

#### Description of tasks to be completed
- Design wireframes for the app, add them in a wireframes directory in the root directory and link them to the README.
- Determine the color palette for them and update the `color.xml` file with the new palettes.

#### How should this be manually tested?
- Navigate to the `wireframes` folder in the root directory and click on each mockup to view them.
- You should be able to see mockups as shown below.

Main screen
main screen

Detail screen
details screen

Share screen
share

#### Any background context you want to provide?
No

#### What are the relevant Pivotal Tracker Stories?
[#158792524](https://www.pivotaltracker.com/story/show/158792524)
[#159051218](https://www.pivotaltracker.com/story/show/159051218)

### CODE REVIEW

**Comment by wasswa-derick** [comment]
@petermwash 

Could you please consider designing a mockup screen for the share functionality (share chooser would be enough).

**Comment by wasswa-derick** [comment]
@petermwash 
Kindly squash your commit to at most 3.

**Comment by petermwash** [comment]
@wasswa-derick 
On it

**Comment by petermwash** [comment]
@wasswa-derick 
Done.

**Review by wasswa-derick — APPROVED** [review]
LGTM

**Pull request merged**
